package]
name = "starkingdoms-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.22.0"
futures = "0.1"
tokio = { version = "0.1"}
tokio-tls = { version = "0.2.0" }
